//
//  SearchPresenter.swift
//  iMusic
//
//  Created by MacService on 21.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
  func presentSomething(response: Search.Something.Response)
}

class SearchPresenter: SearchPresentationLogic {
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Search.Something.Response) {
    let results = response.searchResponse?.results ?? []
    let cells = results.map { Search.Something.ViewModel.Cell(iconUrlString: $0.artworkUrl100 ?? "",
                                                              trackName: $0.trackName,
                                                              artistName: $0.artistName,
                                                              collectionName: $0.collectionName ?? "",
                                                              previewUrl: $0.previewUrl)}
    let viewModel = Search.Something.ViewModel(cells: cells)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
