//
//  SearchModels.swift
//  iMusic
//
//  Created by MacService on 21.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  enum Something {
    struct Request {
      var searchText: String
    }
    struct Response {
      var searchResponse: SearchResponse?
    }
    struct ViewModel {
      var cells: [Cell]
      struct Cell: TrackCellViewModel {
        var iconUrlString: String
        var trackName: String
        var artistName: String
        var collectionName: String
        var previewUrl: String?
      }
    }
  }
}
